### ISSUE TITLE
Null Reference Exception for net47 Console App referencing netstandard library using 2.0.0-Alpha3

### ISSUE THREAD

**Issue by chris31389** [toddams/RazorLight#122]
Hi,

There is a null reference error when trying to call `RazorLightEngine.CompileRenderAsync(...)` from net47 console application referencing another project.

```
   at RazorLight.Compilation.DefaultMetadataReferenceManager.Resolve(Assembly assembly)
   at RazorLight.Compilation.RoslynCompilationService.EnsureOptions()
   at RazorLight.Compilation.RoslynCompilationService.get_ParseOptions()
   at RazorLight.Compilation.RoslynCompilationService.CreateCompilation(String compilationContent, String assemblyName)
   at RazorLight.Compilation.RoslynCompilationService.CompileAndEmit(GeneratedRazorTemplate razorTemplate)
   at RazorLight.TemplateFactoryProvider.CreateFactory(GeneratedRazorTemplate razorTemplate)
   at RazorLight.TemplateFactoryProvider.<CreateFactoryAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at RazorLight.RazorLightEngine.<CompileTemplateAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at RazorLight.RazorLightEngine.<CompileRenderAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at ClassLibrary1.Class1.GetTemplateStringFromFile() in D:\Projects\RazorEngineParser4\ClassLibrary1\Class1.cs:line 29
   at RazorEngineParser4.Program.Main(String[] args) in D:\Projects\RazorEngineParser4\RazorEngineParser4\Program.cs:line 11
```

To recreate, Create a dotnet core console app, and change the target framework to net47 in the csproj. Create a new dot net standard Library and add the RazorLight NuGet and try to render a cshtml view with a model.

``` csharp
public class Class1
{
    public string GetTemplateStringFromFile()
    {
        string theDirectory = typeof(Class1).Assembly.Location;
        string assemblyLocation = Path.GetDirectoryName(theDirectory);

        IRazorLightEngine razorLightEngine = new EngineFactory().ForFileSystem(assemblyLocation);
        Task<string> compileRenderAsync = razorLightEngine.CompileRenderAsync("ApprovalRequests/ApprovalRequestTemplate.cshtml",
            new ApprovalRequestTemplateModel { Name = "Chris", Title = "MyRepo" });

        string result = compileRenderAsync.GetAwaiter().GetResult();
        return result;
    }
}
```

**Comment by chris31389** [comment]
I found that I needed to include `<PreserveCompilationContext>true</PreserveCompilationContext>` in my csproj and install Microsoft.CSharp NuGet package.

here is my csproj

``` xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net47</TargetFramework>
    <PreserveCompilationContext>true</PreserveCompilationContext>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.CSharp" Version="4.4.1" />    
    <PackageReference Include="NETStandard.Library" Version="2.0.0" />    
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\ClassLibrary\ClassLibrary.csproj" />
  </ItemGroup>
</Project>
```
