### ISSUE TITLE
Cannot find reference assembly 'netfx.force.conflicts.dll' file for package netfx.force.conflicts

### ISSUE THREAD

**Issue by kspearrin** [toddams/RazorLight#213]
**Describe the bug**
After upgrading our application to netcoreapp2.1 and ASP.NET Core 2.1 I am now seeing the following errors after deploying to Azure. I also tested on net471 and the same issue occurs.

```
Message:
Cannot find reference assembly 'netfx.force.conflicts.dll' file for package netfx.force.conflicts

Stack Trace:
   at Microsoft.Extensions.DependencyModel.Resolution.ReferenceAssemblyPathResolver.TryResolveAssemblyPaths(CompilationLibrary library, List`1 assemblies)

   at Microsoft.Extensions.DependencyModel.Resolution.CompositeCompilationAssemblyResolver.TryResolveAssemblyPaths(CompilationLibrary library, List`1 assemblies)

   at Microsoft.Extensions.DependencyModel.CompilationLibrary.ResolveReferencePaths(ICompilationAssemblyResolver resolver, List`1 assemblies)

   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()

   at RazorLight.Compilation.DefaultMetadataReferenceManager.Resolve(Assembly assembly)

   at RazorLight.Compilation.RoslynCompilationService.EnsureOptions()

   at RazorLight.Compilation.RoslynCompilationService.get_ParseOptions()

   at RazorLight.Compilation.RoslynCompilationService.CreateCompilation(String compilationContent, String assemblyName)

   at RazorLight.Compilation.RoslynCompilationService.CompileAndEmit(GeneratedRazorTemplate razorTemplate)

   at RazorLight.TemplateFactoryProvider.CreateFactory(GeneratedRazorTemplate razorTemplate)

   at RazorLight.TemplateFactoryProvider.<CreateFactoryAsync>d__4.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at RazorLight.RazorLightEngine.<CompileTemplateAsync>d__10.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at RazorLight.RazorLightEngine.<CompileRenderAsync>d__9.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at Bit.Core.Services.RazorMailService.<SendWelcomeEmailAsync>d__14.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at Bit.Core.Services.BackupMailService.<SendWelcomeEmailAsync>d__15.MoveNext()
```

**To Reproduce**

Deploy ASP.NET Core 2.1 app to Azure App Services.

**Expected behavior**

Should send mail.

**Information (please complete the following information):**
 - OS: Windows
 - Platform: .NET 4.7.1 or netcoreapp2.1, both have the issue
 - RazorLight: version 2.0.0-alpha3

**Comment by heyligengregory** [comment]
I have the same error with version : version 2.0.0-beta1

**Comment by jzabroski** [comment]
@kspearrin @heyligengregory Did you ever find a solution for this issue?  Also, when you say you deployed to Azure, what does that mean?  Sorry, this is a 2 year old issue, so trying to figure out if I can force close it - but I am also trying to wrap my brain around Azure Functions and Azure App Service and how to help people troubleshoot this stuff.  My basic sense is that the Azure deployment model needs work on Microsoft's side, but I'm trying to narrow down the root cause so I can file an appropriate ticket against dotnet org.

**Comment by jzabroski** [comment]
@kspearrin I actually see you did specify Azure App Service-thanks!
