### ISSUE TITLE
System.Security.Cryptography.Xml exception in kestrel

### ISSUE THREAD

**Issue by AndreSteenbergen** [toddams/RazorLight#216]
fail: Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HLGNSTINT35U", Request id "0HLGNSTINT35U:00000001": An unhandled exception was thrown by the application.
System.InvalidOperationException: Cannot find compilation library location for package 'System.Security.Cryptography.Xml'
   at Microsoft.Extensions.DependencyModel.CompilationLibrary.ResolveReferencePaths(ICompilationAssemblyResolver resolver, List`1 assemblies)
   at Microsoft.Extensions.DependencyModel.CompilationLibrary.ResolveReferencePaths()
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   at RazorLight.Compilation.DefaultMetadataReferenceManager.Resolve(DependencyContext dependencyContext)
   at RazorLight.Compilation.RoslynCompilationService.EnsureOptions()
   at RazorLight.Compilation.RoslynCompilationService.get_ParseOptions()
   at RazorLight.Compilation.RoslynCompilationService.CreateSyntaxTree(SourceText sourceText)
   at RazorLight.Compilation.RoslynCompilationService.CreateCompilation(String compilationContent, String assemblyName)
   at RazorLight.Compilation.RoslynCompilationService.CompileAndEmit(IGeneratedRazorTemplate razorTemplate)
   at RazorLight.Compilation.RoslynCompilationService.CompileAsync(IGeneratedRazorTemplate razorTemplate)

**Information (please complete the following information):**
 - OS: Debian in Docker container
 - Platform .NET Core 2.0
 - RazorLight 2.0-beta1

**Comment by toddams** [comment]
Have you tried adding custom metadata references? 

https://github.com/toddams/RazorLight#additional-metadata-references

**Comment by jzabroski** [comment]
@AndreSteenbergen Please let me know if you ever tried @toddams suggestion.
