### ISSUE TITLE
2.0.0-beta1 in Docker on Linux throws error

### ISSUE THREAD

**Issue by sigpop** [toddams/RazorLight#217]
**Describe the bug**
Runs fine in Visual Studio debug using IIS.  Deploy to Docker on a Linux box and this error is thrown:

System.AggregateException: One or more errors occurred. (Cannot find compilation library location for package 'Microsoft.Win32.Registry') ---> System.InvalidOperationException: Cannot find compilation library location for package 'Microsoft.Win32.Registry'
   at Microsoft.Extensions.DependencyModel.CompilationLibrary.ResolveReferencePaths(ICompilationAssemblyResolver resolver, List`1 assemblies)

**To Reproduce**
Deploy this to Docker on Linux:
var engine = new RazorLightEngineBuilder()
              .UseMemoryCachingProvider()
              .Build();
string result = await engine.CompileRenderAsync("templateKey", template, model);

**Expected behavior**
Old ver 1 code worked in both environments.  Not sure if current behavior is by design.

**Information (please complete the following information):**
.Net Core 2.1
VS 2017

**Comment by skolmer** [comment]
I had a similar issue with dotnet core 2.1.5 in docker on linux. I ran into this after migrating from dotnet core 1.2. 
The solution for me was to disable MvcRazorCompileOnPublish as described here: https://github.com/dotnet/sdk/issues/1489

```
2018-10-10T11:07:08.813180781Z System.InvalidOperationException: Cannot find compilation library location for package 'Microsoft.NETCore.App'
2018-10-10T11:07:08.813188981Z    at Microsoft.Extensions.DependencyModel.CompilationLibrary.ResolveReferencePaths(ICompilationAssemblyResolver resolver, List`1 assemblies)
2018-10-10T11:07:08.813193881Z    at Microsoft.Extensions.DependencyModel.CompilationLibrary.ResolveReferencePaths()
2018-10-10T11:07:08.813261784Z    at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
2018-10-10T11:07:08.813269784Z    at RazorLight.Compilation.DefaultMetadataReferenceManager.Resolve(DependencyContext dependencyContext)
2018-10-10T11:07:08.813274284Z    at RazorLight.Compilation.RoslynCompilationService.EnsureOptions()
2018-10-10T11:07:08.813326386Z    at RazorLight.Compilation.RoslynCompilationService.get_ParseOptions()
2018-10-10T11:07:08.813336086Z    at RazorLight.Compilation.RoslynCompilationService.CreateSyntaxTree(SourceText sourceText)
2018-10-10T11:07:08.813395189Z    at RazorLight.Compilation.RoslynCompilationService.CreateCompilation(String compilationContent, String assemblyName)
2018-10-10T11:07:08.813409989Z    at RazorLight.Compilation.RoslynCompilationService.CompileAndEmit(IGeneratedRazorTemplate razorTemplate)
2018-10-10T11:07:08.813415089Z    at RazorLight.Compilation.RoslynCompilationService.CompileAsync(IGeneratedRazorTemplate razorTemplate)
2018-10-10T11:07:08.813481292Z --- End of stack trace from previous location where exception was thrown ---
2018-10-10T11:07:08.813488792Z    at RazorLight.Compilation.TemplateFactoryProvider.CompileAsync(IGeneratedRazorTemplate razorTemplate)
2018-10-10T11:07:08.813492892Z    at RazorLight.Compilation.TemplateFactoryProvider.CreateFactoryAsync(String templateKey)
2018-10-10T11:07:08.813545094Z    at RazorLight.RazorLightEngine.CompileTemplateAsync(String key)
2018-10-10T11:07:08.813552095Z    at RazorLight.RazorLightEngine.CompileRenderAsync(String key, Object model, Type modelType, ExpandoObject viewBag)
```
