### ISSUE TITLE
`CompileRenderAsync` fails to find `System.Threading.AccessControl` with AI SQL diagnostics enabled in Azure App Service

### ISSUE THREAD

**Issue by kevin-david** [toddams/RazorLight#247]
**Describe the bug**
Calling `CompileRenderAsync`:
- On embedded resource `cshtml` files 
- In an [Azure App Service](https://azure.microsoft.com/en-us/services/app-service/) execution environment 
- Targeting `netcoreapp2.2` for the web app / `netstandard2.0` for a class library with the templates
- With the [Application Insights SQL dependency tracking](https://docs.microsoft.com/en-us/azure/azure-monitor/app/asp-net-dependencies) enabled

Results in `FileNotFoundException`s for system reference assemblies being thrown from RazorLight, even with `MvcRazorExcludeRefAssembliesFromPublishDeploy` turned on. `System.Threading.AccessControl` is one example, `System.CodeDom` is another.

**To Reproduce**
- Create two projects, one targeting `netstandard2.0` (a class library) and a web project targeting `netcoreapp2.2` 
- Embed a template `cshtml` file in the class library
- Build engine like this (had to do it this way to get unit tests for rendering working):
```csharp
new RazorLightEngineBuilder()
                .UseEmbeddedResourcesProject(
                    Assembly.GetExecutingAssembly(),
                    rootNamespace: myModelNamespaceRelativeToAssemblyRoot)
                .SetOperatingAssembly(Assembly.GetExecutingAssembly())
                .Build();
```
- Add something that calls `CompileRenderAsync` like this:
```csharp
 Engine.CompileRenderAsync(EmbeddedResourceFilename, myModel);
```
- Set `MvcRazorExcludeRefAssembliesFromPublishDeploy` to false in the class library (this allows it to work at all in this scenario)
- `dotnet publish` the web project, which references the `netstandard2.0` class library
- Deploy the project to an Azure App Service
- Enable the SQL diagnostics option:
![image](https://user-images.githubusercontent.com/1923186/54030735-84b85800-417a-11e9-9b8a-86a22b4368d7.png)
- Call your API that renders a razor template. Observe failure. Disable the option, retry the same operation, observe success.

**Expected behavior**
Email renders without exception

**Information (please complete the following information):**
 - OS: Azure App Service
 - Platform: .NET Core 2.2
 - RazorLight version: 2.0-beta1 (latest as of this writing?)
 - Visual Studio version: N/A

**Additional context**
I realize it's a complicated repro, and the maintainer is doing this for free in his free time, but I hope this at least helps someone else debug this issue. I'm not sure what the SQL dependency tracking is doing to cause this issue - maybe dropping assemblies in strange places on the Azure App Service VM?

Unfortinuately, I have not been able to reproduce this issue locally on Windows or Linux functionally or by writing unit tests that I would expect to fail.

 The workarounds are to disable SQL tracking, or not target `netcoreapp2.2` - I know for a fact targeting `net47` instead works fine, but that's obviously not ideal.

Full stack trace:
```
System.IO.FileNotFoundException: Could not load file or assembly 'System.Threading.AccessControl, Version=0.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
File name: 'System.Threading.AccessControl, Version=0.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, IntPtr ptrLoadContextBinder)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, IntPtr ptrLoadContextBinder)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at RazorLight.Compilation.DefaultMetadataReferenceManager.GetReferencedAssemblies(Assembly a, IEnumerable`1 excludedAssemblies, HashSet`1 visitedAssemblies)+MoveNext()
   at RazorLight.Compilation.DefaultMetadataReferenceManager.GetReferencedAssemblies(Assembly a, IEnumerable`1 excludedAssemblies, HashSet`1 visitedAssemblies)+MoveNext()
   at RazorLight.Compilation.DefaultMetadataReferenceManager.GetReferencedAssemblies(Assembly a, IEnumerable`1 excludedAssemblies, HashSet`1 visitedAssemblies)+MoveNext()
   at RazorLight.Compilation.DefaultMetadataReferenceManager.GetReferencedAssemblies(Assembly a, IEnumerable`1 excludedAssemblies, HashSet`1 visitedAssemblies)+MoveNext()
   at RazorLight.Compilation.DefaultMetadataReferenceManager.GetReferencedAssemblies(Assembly a, IEnumerable`1 excludedAssemblies, HashSet`1 visitedAssemblies)+MoveNext()
   at System.Linq.Set`1.UnionWith(IEnumerable`1 other)
   at System.Linq.Enumerable.UnionIterator`1.FillSet()
   at System.Linq.Enumerable.UnionIterator`1.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at RazorLight.Compilation.DefaultMetadataReferenceManager.Resolve(Assembly assembly, DependencyContext dependencyContext)
   at RazorLight.Compilation.DefaultMetadataReferenceManager.Resolve(Assembly assembly)
   at RazorLight.Compilation.RoslynCompilationService.EnsureOptions()
   at RazorLight.Compilation.RoslynCompilationService.get_ParseOptions()
   at RazorLight.Compilation.RoslynCompilationService.CreateSyntaxTree(SourceText sourceText)
   at RazorLight.Compilation.RoslynCompilationService.CreateCompilation(String compilationContent, String assemblyName)
   at RazorLight.Compilation.RoslynCompilationService.CompileAndEmit(IGeneratedRazorTemplate razorTemplate)
   at RazorLight.Compilation.RazorTemplateCompiler.CompileAndEmit(RazorLightProjectItem projectItem)
   at RazorLight.Compilation.RazorTemplateCompiler.OnCacheMissAsync(String templateKey)
--- End of stack trace from previous location where exception was thrown ---
   at RazorLight.EngineHandler.CompileTemplateAsync(String key)
   at RazorLight.EngineHandler.CompileRenderAsync[T](String key, T model, ExpandoObject viewBag)
```

**Comment by everix1992** [comment]
Leaving this here since it's slightly relevant. I ran into this same exception, but in an Azure Functions project and was able to resolve it by adding the Nuget Package System.Threading.AccessControl to my project. Not the most ideal solution, but at least it worked for me

**Comment by jzabroski** [comment]
@everix1992 did you try the advice in the FAQ? You can also try `<PublishTrimmed>False</PublishTrimmed>` in your root csproj

**Comment by jzabroski** [comment]
@kevin-david Did you try adding `System.Threading.AccessControl` nuget package to your root csproj?  Then, also, did you add `<PublishTrimmed>False</PublishTrimmed>` in your root csproj? The problem with this bug is I think I need an Azure App Service account in order to reproduce it, as I dont believe this feature is available locally.

**Comment by kevin-david** [comment]
@jzabroski i did not - i ended up switching to [Razor Class Libraries](https://docs.microsoft.com/en-us/aspnet/core/razor-pages/ui-class) after some really frustrating experiences trying to update dependencies.

**Comment by jzabroski** [comment]
I understand that you had some really frustrating experiences trying to update dependencies.  The .NET nuget/msbuild build system is very sophisticated, and it has taken me years of troubleshooting war stories to come anywhere close to mastery.

For my own education, can you share with me how you use Razor Class Libraries?  I looked at the tutorial, but what are you looking to accomplish.  Something like, "I want to deploy using Azure App Service a set of razor templates and razor template rendering service so that I can generate emails via templates for my application that is also deployed on Azure App Service..."

I realize this doesn't benefit you directly, but I'd like to course correct and smooth over problems, by better understanding various scenarios.  Thanks in advance for your patience and help.

**Comment by kevin-david** [comment]
Sure. It's almost exactly what the tutorial spells out. 

I have a mostly monolithic application (technically two Azure App Services with one mostly shared code base) deployed as an Azure App Service plan. Part of that ASP.NET core web app has email templates that were built using Razor `.cshtml` files - so I was essentially trying to find a reliable way to render those emails with models into `string` objects.

It's a bit ugly right now and pulls in some unnecessary dependencies at runtime (and I need to mock/stub out things like the `IWebHostEnvironment`, `DiagnosticListener`, `ViewDataDictionary`, `TempDataDictionary`, and `HtmlHelperOptions`) but the end result is I can render emails either via the web app OR via unit tests by calling into the `RazorViewToStringRenderer` I have exposed as a part of the class library.

Here's the entirety of the code, if you're interested:

<details>

```csharp
public class RazorViewToStringRenderer : IRazorViewToStringRenderer
{
    static RazorViewToStringRenderer()
    {
        s_sem = new SemaphoreSlim(1, 1);
    }

    public RazorViewToStringRenderer(
        IRazorViewEngine viewEngine,
        ITempDataProvider tempDataProvider,
        IServiceProvider serviceProvider,
        ILogger<RazorViewToStringRenderer>? logger)
    {
        m_viewEngine = viewEngine;
        m_tempDataProvider = tempDataProvider;
        m_serviceProvider = serviceProvider;
        m_logger = logger ?? NullLogger<RazorViewToStringRenderer>.Instance;
    }

    public async Task<string> RenderViewToStringAsync<TModel>(string viewName, TModel model)
    {
        await s_sem.WaitAsync();
        try
        {
            ActionContext actionContext = GetActionContext();
            IView view = FindView(actionContext, viewName);
            using (var output = new StringWriter())
            {
                var viewContext = new ViewContext(
                    actionContext,
                    view,
                    new ViewDataDictionary<TModel>(
                        metadataProvider: new EmptyModelMetadataProvider(),
                        modelState: new ModelStateDictionary())
                    { Model = model },
                    new TempDataDictionary(
                        actionContext.HttpContext,
                        m_tempDataProvider),
                    output,
                    new HtmlHelperOptions());
                await view.RenderAsync(viewContext);
                return output.ToString();
            }
        }
        finally
        {
            s_sem.Release();
        }
    }

    private IView FindView(ActionContext actionContext, string viewName)
    {
        ViewEngineResult? getViewResult = null;
        try
        {
            getViewResult = m_viewEngine.GetView("~/", viewPath: viewName, isMainPage: true);
            if (getViewResult.Success)
            {
                return getViewResult.View;
            }
        }
        catch (Exception ex)
        {
            m_logger.LogWarning($"GetView call failed: {ex}");
        }
        ViewEngineResult findViewResult = m_viewEngine.FindView(actionContext, viewName, isMainPage: true);
        if (findViewResult != null && findViewResult.Success)
        {
            return findViewResult.View;
        }
        getViewResult ??= findViewResult;
        string errorMessage = $"Unable to find view `{viewName}`.";
        if (getViewResult != null)
        {
            IEnumerable<string> searchedLocations = getViewResult.SearchedLocations.Concat(
                findViewResult?.SearchedLocations ?? Enumerable.Empty<string>());
            errorMessage = string.Join(
                Environment.NewLine,
                new[] { $"{errorMessage} The following locations were searched:" }.Concat(searchedLocations));
        }
        throw new InvalidOperationException(errorMessage);
    }
    
    private ActionContext GetActionContext()
    {
        var httpContext = new DefaultHttpContext
        {
            RequestServices = m_serviceProvider
        };
        return new ActionContext(httpContext, new RouteData(), new ActionDescriptor());
    }

    /// <summary>
    /// This exists to synchronize access to the underlying .NET classes it depends on, because those
    /// classes aren't thread safe. https://github.com/aspnet/Mvc/issues/8260#issuecomment-414517659
    /// https://github.com/aspnet/Mvc/issues/5106
    /// </summary>
    private static readonly SemaphoreSlim s_sem;

    private readonly ILogger<RazorViewToStringRenderer> m_logger;
    private readonly IServiceProvider m_serviceProvider;
    private readonly ITempDataProvider m_tempDataProvider;
    private readonly IRazorViewEngine m_viewEngine;
}

public static class ServiceExtensions
{
    public static IServiceCollection ConfigureRazorEmails(this IServiceCollection services)
    {
        var thisAssembly = Assembly.GetExecutingAssembly();
        string assemblyName = thisAssembly.GetName().Name!;
        // Configure stubs for services that don't exist outside of the web. Inspiration:
        // https://long2know.com/2017/08/rendering-and-emailing-embedded-razor-views-with-net-core/
        // https://github.com/aspnet/Razor/issues/2122
        services.TryAddSingleton<IWebHostEnvironment>(new StubHostEnvironment
        {
            // https://github.com/aspnet/Razor/issues/2122#issuecomment-371868901
            ApplicationName = assemblyName
        });
        
        var diagListener = new DiagnosticListener(assemblyName);
        services.TryAddSingleton<DiagnosticSource>(diagListener);
        services.TryAddSingleton(diagListener);
        services.TryAddSingleton<ObjectPoolProvider, DefaultObjectPoolProvider>();
        services
            .AddMvcCore()
            .AddRazorPages()
            // Kevin 2019-01-29: AFAICT `AddAuthorization` isn't actually _needed_ at runtime but prevents
            // startup DI errors
            .AddAuthorization()
            .AddRazorRuntimeCompilation();
        // This can't be long-lived: https://github.com/aspnet/Mvc/issues/8260#issuecomment-414517659
        // https://github.com/aspnet/Mvc/issues/5106
        services.AddTransient<IRazorViewToStringRenderer, RazorViewToStringRenderer>();

        // The views aren't actually embedded in _this_ assembly, but they are in the .Views assembly
        // right next to this one, so load them from there.
        services.Configure<MvcRazorRuntimeCompilationOptions>(options =>
        {
            options.FileProviders.Clear(); // Only use the next provider we add
            // Removes unnecessary filesystem-based one (also gets L1 tests working)
            options.FileProviders.Add(new EmbeddedFileProvider(thisAssembly));
        });

        return services;
    }

    private class StubHostEnvironment : IWebHostEnvironment
    {
        public string ApplicationName { get; set; } = default!;
        public IFileProvider ContentRootFileProvider { get; set; } = default!;
        public string ContentRootPath { get; set; } = default!;
        public string EnvironmentName { get; set; } = default!;
        public IFileProvider WebRootFileProvider { get; set; } = default!;
        public string WebRootPath { get; set; } = default!;
    }
}
```

Then at app startup, I just call `services.ConfigureRazorEmails()` inside `ConfigureServices`.

</details>

**Comment by jzabroski** [comment]
Hi Kevin, Thanks, that is basically what I'm interested in hearing.  I think rather than me spend time debugging each person's individual set-up, it makes more sense for me to define some best practices samples people can fork off of, and then ask them, ok, which sample did you base your logic on?  And you captured beautifully what you want to achieve - unit test code coverage, and deploy via web app.

**Comment by tghamm** [comment]
Just figured I'd toss in there, we're experiencing this exact issue in pretty much the same configuration, only, with .net core 3.1

**Comment by jzabroski** [comment]
@tghamm Just to make sure I capture the problem: When you say pretty much the same configuration, do you mean:

1. Azure App Service
2. AI SQL Diagnostics enabled
3. Only difference is you're using .NET Core 3.1

As a dirty workaround, you can consider creating a DirtyAssemblyResolveHelper class that forces the .NET runtime to load whatever version of the DLL you have available.  I am not sure that will work, but it might be worth a try.

**Comment by tghamm** [comment]
@jzabroski precisely.  Azure App Service, AI SQL Diagnostics enabled (disabling rectifies the issue), and we're using .NET Core 3.1.

**Comment by jzabroski** [comment]
@tghamm It's important to realize this is not our bug.  This belongs with either dotnet org or with Azure App Service.  The way you can troubleshoot this problem to help get Microsoft to move the ball on this problem is as follows:

1. Read https://docs.microsoft.com/en-us/dotnet/core/dependency-loading/understanding-assemblyloadcontext
2. Use `Type.GetType("TypeNameThatIsFailedToBeFound").Assembly to log the assembly location of the type as the .NET Core Runtime thinks it exists, vs. the one that the particular call graph wants loaded
3. Use the tricks explained in https://docs.microsoft.com/en-us/dotnet/core/dependency-loading/understanding-assemblyloadcontext#debugging-type-conversion-issues to layer on top of Type.GetType mentioned above, by running: `System.Runtime.Loader.AssemblyLoadContext.GetLoadContext(Type.GetType("TypeNameThatIsFailedToBeFound").Assembly)`
4. Log your host configured probing paths: https://docs.microsoft.com/en-us/dotnet/core/dependency-loading/default-probing#host-configured-probing-properties
5. Note also `ADDITIONAL_DEPS` https://docs.microsoft.com/en-us/dotnet/core/dependency-loading/default-probing#how-are-the-properties-populated - the article doesn't mention it but all deps.json files can be retrieved also from `System.AppContext.GetData(“APP_CONTEXT_DEPS_FILES”)`, so you should log those as well.

**Comment by jzabroski** [comment]
I submitted a PR to improve the assembly loading debugging docs: https://github.com/dotnet/docs/pull/19958

**Comment by jzabroski** [comment]
@tghamm As one other thought, I see Kevin David never tried setting PublishTrimmed to false.  Can you try that guidance and see if it works? (See: https://github.com/toddams/RazorLight/issues/247#issuecomment-651510802)  Please don't try this in production environment! :)

**Comment by tghamm** [comment]
@jzabroski we played around with this today, and in our case, System.Threading.AccessControl was not part of the project at all.  Simply adding the Nuget package to the project fixed the issue and got us running again.  We spent all day messing with the .Net Core 3.1/App Service/Application Insights combo, and, having recently come from the same stack in .Net 4.5, I'd agree that the AI instrumentation implementation is neither super well documented nor does it behave entirely as one would expect.

**Comment by tghamm** [comment]
@jzabroski appreciate the help and responsiveness!

**Comment by ElementalLogic** [comment]
Adding that reference didn't work for me...

It seems that the .net standard build in the src project refenences old out of date nuget packages. After a lot of faffing, I managed to get a build (in .net Standard) which successfully works in class library used in .net 4.8 and .net 5 projects. But I was still left with this odd error, 

I'm guessing that the compile time process is running in the wrong context so not finding the libraries it needs.. the fix for me was to  use this to process the templates:

  var engine = new RazorLight.RazorLightEngineBuilder().SetOperatingAssembly(Assembly.GetExecutingAssembly()).UseFileSystemProject("F:\\work\\MCI\\dev\\WebApp\\WebApp\\bin\\RazorReports").Build();
            return engine.CompileRenderAsync("test.cshtml", model).Result;



It was changing Assembly.GetCallingAssembly() to Assembly.GetExecutingAssembly()  which fixed it...

**Comment by jzabroski** [comment]
> It seems that the .net standard build in the src project refenences old out of date nuget packages. After a lot of faffing, I managed to get a build (in .net Standard) which successfully works in class library used in .net 4.8 and .net 5 projects. But I was still left with this odd error,

Sorry, can you elaborate what you did?  It sounds like you want to submit a PR?  Thanks.

**Comment by ElementalLogic** [comment]
I'm not sure my changes would be suitable as a release candidate, as I essentially retargeted it to just .net standard 2.0 - on the basis that can be used by .net framework 4.8 and .net 5 projects.. but in the process I noticed there were package references in the project to old versions of nuget packages.. some of these were setup as build target and version specific (for example the .net standard version referencing system.immutable version 1.4) ..  these caused so many problems so I updated them to the latest stable versions. 

That got it working in .net 4.8, but in .net 5 I was getting the message referenced in this thread, to fix that specifically I changed the operating assembly from GetCallingAssembly (as per instructions elsewhere) to GetExecutingAssembly... I hope that makes sense.

**Comment by jzabroski** [comment]
Did you delete your last reply?  Not sure why it didnt show up here.

I think even if it doesn't get accepted as a PR, it is instructive to help diagnose stuff for others.

**Comment by ElementalLogic** [comment]
I did, simply because on rereading the entire thread I realised that it wasn't totally relevant. In the interests of full disclosure the reply was essentially this:

Out of the box I couldn't get Razorlight to work in a class library which was referenced from .net framework 4.8 and .net 5 projects. After getting the source I had to fix a number of issues and as part of that I made the project only target .Net Standard 2.0 - because that can be referenced from both 4.8 and 5. In the project there are different versions of the nuget packages which were target dependant. For .net standard 2.0 there were references to specific old versions of nuget packages, even updating the reference in Nuget Package manager didn't help (because it only changed them for certain targets), so I had to tidy them up in the cs project file (remove the build qualifier) manually then update them to the latest version.  After I'd done all that, I started getting the message in this thread from my .net 5 project. It came about through a different mechanism, but I believe it's linked to the same issue - that when compiling the razor view it traverses the runtime assemblies looking for specific versions.  The final part of the puzzle was changing the operating assembly to the executing assembly (as opposed to the calling assembly) - which in essence forced it to use .Net Standard. 

I'm not sure I understand the rationale of providing .net core targeted versions when .net standard libraries will work in .net core (albeit 2+)...
