### ISSUE TITLE
Mono.Posix required?

### ISSUE THREAD

**Issue by jgmdavies** [toddams/RazorLight#437]
Installed in VS 2019 using the recommended:  Install-Package RazorLight -Version 2.0.0-rc.3
WinForms, .NET Framework 4.8.2.

I get:

**System.IO.FileNotFoundException: Could not load file or assembly 'Mono.Posix, Version=4.0.0.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756' or one of its dependencies. The system cannot find the file specified.**

Is Mono required for RazorLight?

Thanks,
Jim

**Comment by jzabroski** [comment]
Can you please provide more details

**Comment by jzabroski** [comment]
E.g. full stack trace

**Comment by jgmdavies** [comment]
System.IO.FileNotFoundException: Could not load file or assembly 'Mono.Posix, Version=4.0.0.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756' or one of its dependencies. The system cannot find the file specified.
File name: 'Mono.Posix, Version=4.0.0.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756'
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at RazorLight.Compilation.DefaultMetadataReferenceManager.<GetReferencedAssemblies>d__13.MoveNext()
   at RazorLight.Compilation.DefaultMetadataReferenceManager.<GetReferencedAssemblies>d__13.MoveNext()
   at RazorLight.Compilation.DefaultMetadataReferenceManager.<GetReferencedAssemblies>d__13.MoveNext()
   at RazorLight.Compilation.DefaultMetadataReferenceManager.<GetReferencedAssemblies>d__13.MoveNext()
   at System.Linq.Enumerable.<UnionIterator>d__67`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at RazorLight.Compilation.DefaultMetadataReferenceManager.Resolve(Assembly assembly, DependencyContext dependencyContext)
   at RazorLight.Compilation.DefaultMetadataReferenceManager.Resolve(Assembly assembly)
   at RazorLight.Compilation.RoslynCompilationService.EnsureOptions()
   at RazorLight.Compilation.RoslynCompilationService.get_ParseOptions()
   at RazorLight.Compilation.RoslynCompilationService.CreateSyntaxTree(SourceText sourceText)
   at RazorLight.Compilation.RoslynCompilationService.CreateCompilation(String compilationContent, String assemblyName)
   at RazorLight.Compilation.RoslynCompilationService.CompileAndEmit(IGeneratedRazorTemplate razorTemplate)
   at RazorLight.Compilation.RazorTemplateCompiler.CompileAndEmit(RazorLightProjectItem projectItem)
   at RazorLight.Compilation.RazorTemplateCompiler.OnCacheMissAsync(String templateKey)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at RazorLight.EngineHandler.<CompileTemplateAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at RazorLight.EngineHandler.<CompileRenderAsync>d__20`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at xxx.HtmlGenerator.<GenerateFromFileAsync>d__3.MoveNext() in D:\xxx\HtmlGenerator.cs:line 45

=== Pre-bind state information ===
LOG: DisplayName = Mono.Posix, Version=4.0.0.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756
 (Fully-specified)
LOG: Appbase = file:///D:/xxx/bin/Debug/
LOG: Initial PrivatePath = NULL
Calling assembly : RazorLight, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null.
===
LOG: This bind starts in default load context.
LOG: Using application configuration file: D:\xxx\bin\Debug\xxx.exe.Config
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config.
LOG: Post-policy reference: Mono.Posix, Version=4.0.0.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756
LOG: Attempting download of new URL file:///D:/xxx/bin/Debug/Mono.Posix.DLL.
LOG: Attempting download of new URL file:///D:/xxx/bin/Debug/Mono.Posix/Mono.Posix.DLL.
LOG: Attempting download of new URL file:///D:/xxx/bin/Debug/Mono.Posix.EXE.
LOG: Attempting download of new URL file:///D:/xxxbin/Debug/Mono.Posix/Mono.Posix.EXE.

**Comment by jzabroski** [comment]
This doesn't make a lot of sense.  Are you using another package like Topshelf.Unix to deploy your app?

**Comment by jzabroski** [comment]
If you can copy-paste your csproj with your packages.config, that would be helpfu.  Don't believe WinForms supports modern csproj file format.

**Comment by toddams** [comment]
Mono is not required for the project to run
