### ISSUE TITLE
System.IO.IOException: Too many open files

### ISSUE THREAD

**Issue by rhegner** [toddams/RazorLight#54]
My software periodically compiles mail templates using RazorLight. On one of the installations (running under Linux) I got the following exception:

    System.IO.IOException: Too many open files
       at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
       at Interop.CheckIo[TSafeHandle](TSafeHandle handle, String path, Boolean isDirectory, Func`2 errorRewriter)
       at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
       at System.IO.UnixFileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, FileStream parent)
       at System.IO.UnixFileSystem.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, FileStream parent)
       at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
       at Microsoft.Extensions.DependencyModel.FileWrapper.OpenRead(String path)
       at Microsoft.Extensions.DependencyModel.DependencyContextLoader.LoadEntryAssemblyContext(IDependencyContextReader reader)
       at Microsoft.Extensions.DependencyModel.DependencyContextLoader.Load(Assembly assembly)
       at RazorLight.UseEntryAssemblyMetadataResolver.GetMetadataReferences()
       at System.Threading.LazyInitializer.EnsureInitializedCore[T](T& target, Boolean& initialized, Object& syncLock, Func`1 valueFactory)
       at RazorLight.Compilation.RoslynCompilerService.get_CompilationReferences()
       at RazorLight.Compilation.RoslynCompilerService.Compile(CompilationContext context)
       at RazorLight.EngineCore.CompileSource(ITemplateSource templateSource, ModelTypeInfo modelTypeInfo)

This looks like a resource leak caused by RazorLight.

I noticed that none of the RazorLight classes implement the IDisposable interface. What do I need to do to make sure RazorLight releases its (unmanaged) resources properly? Or is it a bug in RazorLight?

**Comment by toddams** [comment]
Do you use Mono or NETCore?

**Comment by rhegner** [comment]
I'm using .NetCore

**Comment by toddams** [comment]
I think it's not a RazorLight issue.

Take a look at this ticket - https://github.com/dotnet/corefx/issues/12503

One of the proposed solutions - is to increase ````ulimit```` at your OS.
