### ISSUE TITLE
System.Collections.Immutable error when running from net461 test project

### ISSUE THREAD

**Issue by mcintyre321** [toddams/RazorLight#59]
Hi again. I'm getting an error when I try to use RazorLight from my net461 xunit test project.

Have you seen anything like this before? 

![Error](https://snag.gy/9VOMGw.jpg)

I'm doing multi-framework targeting for my FormFactory.Standalone project so it's not surprising things aren't 100% working...

```
System.IO.FileLoadException occurred
  HResult=0x80131040
  Message=Could not load file or assembly 'System.Collections.Immutable, Version=1.1.37.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
  Source=RazorLight
  StackTrace:
   at RazorLight.Compilation.RoslynCompilerService.Compile(CompilationContext context) in C:\Users\Harry\OneDrive\stuff\FormFactory\RazorLight\Compilation\RoslynCompilerService.cs:line 108
   at FormFactory.Standalone.EngineFactory.<>c__DisplayClass1_0.<CreateEmbedded>b__0(String key) in C:\Users\Harry\OneDrive\stuff\FormFactory\FormFactory.Standalone\EngineFactory.cs:line 33
   at RazorLight.Templating.DefaultPageFactory.CreateFactory(String key) in C:\Users\Harry\OneDrive\stuff\FormFactory\RazorLight\Templating\DefaultPageFactory.cs:line 22
   at RazorLight.Templating.DefaultPageLookup.GetPage(String key) in C:\Users\Harry\OneDrive\stuff\FormFactory\RazorLight\Templating\DefaultPageLookup.cs:line 27
   at RazorLight.RazorLightEngine.Parse(String key, Object model, Type modelType, ExpandoObject viewBag, Action`1 prerenderCallback) in C:\Users\Harry\OneDrive\stuff\FormFactory\RazorLight\RazorLightEngine.cs:line 102
   at RazorLight.RazorLightEngine.Parse[T](String key, T model, ExpandoObject viewBag, Action`1 prerenderCallback) in C:\Users\Harry\OneDrive\stuff\FormFactory\RazorLight\RazorLightEngine.cs:line 73
   at FormFactory.Standalone.RazorTemplateHtmlHelper.Partial(String partialName, Object model, ViewData viewData) in C:\Users\Harry\OneDrive\stuff\FormFactory\FormFactory.Standalone\RazorTemplateHtmlHelper.cs:line 83
   at FormFactory.Standalone.RenderExtension.Render(PropertyVm propertyVm, RazorTemplateHtmlHelper html) in C:\Users\Harry\OneDrive\stuff\FormFactory\FormFactory.Standalone\RenderExtension.cs:line 21
   at FormFactory.Standalone.RenderExtension.Render(IEnumerable`1 properties, RazorTemplateHtmlHelper html) in C:\Users\Harry\OneDrive\stuff\FormFactory\FormFactory.Standalone\RenderExtension.cs:line 14
   at FormFactory.NetFramework.Tests.BasicPropertyTests.CanRenderAPropertyWithoutThrowingAnException() in C:\Users\Harry\OneDrive\stuff\FormFactory\FormFactory.NetFramework.Tests\BasicPropertyTests.cs:line 17
```

**Comment by toddams** [comment]
Are you sure you have that assembly referenced in your main assembly?

**Comment by mcintyre321** [comment]
So I get that error if I unless U explicitly install 1.1.37 into the entry project. The problem is that the RazorLight depends on Microsoft.CodeAnalysis.CSharp (>= 1.3.0) which depends on Microsoft.CodeAnalysis.Common (= 1.3.0) which depends on System.Collections.Immutable (>= 1.3.1)

So it ends up with a higher version of System.Collections.Immutable (1.3.1 or above) and then it throws the error. I can workaround it with a manual package install of 1.1.37 (I get some warnings from Nuget about a package downgrade when I do this) but it doesn't seem ideal...

**Comment by MFFoX** [comment]
I get this error for quite a few assemblies (all requiring version 4.0.0.0) on `Parse`
>An exception of type 'System.IO.FileLoadException' occurred in mscorlib.dll and wasn't handled before a managed/native boundary
Additional information: Could not load file or assembly 'System.Security.Cryptography.Algorithms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040) occurred

- `System.IO.FileSystem.Primitives`
- `System.IO.FileSystem`
- `System.Security.Cryptography.Algorithms`

I successfully downgraded from 4.3.0  to 4.0.0 for `System.IO.FileSystem.Primitives` and `System.IO.FileSystem` but `System.Security.Cryptography.Algorithms` doesn't have the required package available on nuget.

![versions screenshot](https://user-images.githubusercontent.com/1459856/28090323-8dfe17ac-6651-11e7-8658-fa9245bfab3b.png)

https://www.nuget.org/packages/System.Security.Cryptography.Algorithms/

**Comment by MFFoX** [comment]
Related: https://github.com/dotnet/corefx/issues/15570
