### ISSUE TITLE
You must add a reference to assembly System.Runtime, Version=4.1.0.0

### ISSUE THREAD

**Issue by kspearrin** [toddams/RazorLight#79]
Hi,
I have been using this library just fine on Full Framework (4.6.1).

I am now trying to port my project to netcoreapp2.0 (preview). Everything is working fine now except when I try to compile mail templates using RazorLight 1.1.0.

Implementation
=======

https://github.com/bitwarden/core/blob/master/src/Core/Services/Implementations/RazorViewMailService.cs

Error when trying to compile mail templates with RazorLight
===========

```
dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.0-preview2-25407-01\System.Xml.XDocument.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.0-preview2-25407-01\System.Private.Xml.Linq.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Microsoft.Extensions.DependencyInjection.DataProtectionServices:Information: User profile is available. Using 'C:\Users\kyles\AppData\Local\ASP.NET\DataProtection-Keys' as key repository and Windows DPAPI to encrypt keys at rest.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.0-preview2-25407-01\System.Runtime.Serialization.Formatters.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker:Information: Executing action method Bit.Api.Controllers.AccountsController.PostRegister (Api) with arguments (Bit.Core.Models.Api.RegisterRequestModel) - ModelState is Valid
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Users\kyles\.nuget\packages\microsoft.aspnetcore.cryptography.keyderivation\1.1.2\lib\netstandard1.3\Microsoft.AspNetCore.Cryptography.KeyDerivation.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\store\x64\netcoreapp2.0\system.data.sqlclient\4.4.0-preview2-25405-01\runtimes\win\lib\netstandard2.0\System.Data.SqlClient.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.0-preview2-25407-01\System.Transactions.Local.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.0-preview2-25407-01\System.Text.RegularExpressions.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.0-preview2-25407-01\System.Collections.NonGeneric.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.0-preview2-25407-01\System.Xml.XmlDocument.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\store\x64\netcoreapp2.0\system.text.encoding.codepages\4.4.0-preview2-25405-01\runtimes\win\lib\netcoreapp2.0\System.Text.Encoding.CodePages.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.0-preview2-25407-01\System.Collections.Immutable.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.0-preview2-25407-01\System.Reflection.Metadata.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Users\kyles\.nuget\packages\microsoft.dotnet.platformabstractions\1.1.2\lib\netstandard1.3\Microsoft.DotNet.PlatformAbstractions.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.0-preview2-25407-01\System.Threading.Tasks.Parallel.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Exception thrown: 'RazorLight.TemplateCompilationException' in RazorLight.dll
Exception thrown: 'RazorLight.TemplateCompilationException' in System.Private.CoreLib.dll
Exception thrown: 'RazorLight.TemplateCompilationException' in System.Private.CoreLib.dll
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.0-preview2-25407-01\System.Diagnostics.StackTrace.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.0.0-preview2-25407-01\System.IO.MemoryMappedFiles.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
Bit.Api.Utilities.ExceptionHandlerFilterAttribute:Error: Failed to compile generated Razor template:
- (3:17) The type or namespace name 'Linq' does not exist in the namespace 'System' (are you missing an assembly reference?)
- (6:17) The type or namespace name 'Threading' does not exist in the namespace 'System' (are you missing an assembly reference?)
- (8:32) The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
- (19:35) The return type of an async method must be void, Task or Task<T>
- (19:30) The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
- (19:30) Predefined type 'System.Object' is not defined or imported
- (19:30) The type or namespace name 'Task' could not be found (are you missing a using directive or an assembly reference?)
- (19:35) 'iaudzgaf_03d.ExecuteAsync()': return type must be 'Task' to match overridden member 'TemplatePage.ExecuteAsync()'
- (19:35) The type 'Task' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Threading.Tasks, Version=4.0.10.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
- (11:8) Predefined type 'System.Void' is not defined or imported
- (11:15) Predefined type 'System.Void' is not defined or imported
- (2:4) Predefined type 'System.String' is not defined or imported
- (2:13) Predefined type 'System.String' is not defined or imported
- (28:25) Predefined type 'System.String' is not defined or imported
- (28:12) The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
- (28:12) Predefined type 'System.Object' is not defined or imported
- (28:12) Predefined type 'System.Void' is not defined or imported
- (32:25) Predefined type 'System.String' is not defined or imported
- (32:12) The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
- (32:12) Predefined type 'System.Object' is not defined or imported
- (32:12) Predefined type 'System.Void' is not defined or imported
- (39:25) Predefined type 'System.String' is not defined or imported
- (39:12) The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
- (39:12) Predefined type 'System.Object' is not defined or imported
- (39:12) Predefined type 'System.Void' is not defined or imported
- (46:25) Predefined type 'System.String' is not defined or imported
- (46:12) The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
- (46:12) Predefined type 'System.Object' is not defined or imported
- (46:12) Predefined type 'System.Void' is not defined or imported
- (54:25) Predefined type 'System.String' is not defined or imported
- (54:12) The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
- (54:12) Predefined type 'System.Object' is not defined or imported
- (54:12) Predefined type 'System.Void' is not defined or imported
- (58:25) Predefined type 'System.String' is not defined or imported
- (58:12) The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
- (58:12) Predefined type 'System.Object' is not defined or imported
- (58:12) Predefined type 'System.Void' is not defined or imported
- (63:25) Predefined type 'System.String' is not defined or imported
- (63:12) The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
- (63:12) Predefined type 'System.Object' is not defined or imported
- (63:12) Predefined type 'System.Void' is not defined or imported
- (72:25) Predefined type 'System.String' is not defined or imported
- (72:12) The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
- (72:12) Predefined type 'System.Object' is not defined or imported
- (72:12) Predefined type 'System.Void' is not defined or imported
- (80:25) Predefined type 'System.String' is not defined or imported
- (80:12) The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
- (80:12) Predefined type 'System.Object' is not defined or imported
- (80:12) Predefined type 'System.Void' is not defined or imported
- (84:25) Predefined type 'System.String' is not defined or imported
- (84:12) The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
- (84:12) Predefined type 'System.Object' is not defined or imported
- (84:12) Predefined type 'System.Void' is not defined or imported
- (92:25) Predefined type 'System.String' is not defined or imported
- (92:12) The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
- (92:12) Predefined type 'System.Object' is not defined or imported
- (92:12) Predefined type 'System.Void' is not defined or imported
- (97:25) Predefined type 'System.String' is not defined or imported
- (97:12) The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
- (97:12) Predefined type 'System.Object' is not defined or imported
- (97:12) Predefined type 'System.Void' is not defined or imported
- (102:25) Predefined type 'System.String' is not defined or imported
- (102:12) The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
- (102:12) Predefined type 'System.Object' is not defined or imported
- (102:12) Predefined type 'System.Void' is not defined or imported
- (106:25) Predefined type 'System.String' is not defined or imported
- (106:12) The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
- (106:12) Predefined type 'System.Object' is not defined or imported
- (106:12) Predefined type 'System.Void' is not defined or imported
- (111:25) Predefined type 'System.String' is not defined or imported
- (111:12) The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
- (111:12) Predefined type 'System.Object' is not defined or imported
- (111:12) Predefined type 'System.Void' is not defined or imported
- (122:25) Predefined type 'System.String' is not defined or imported
- (122:12) The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
- (122:12) Predefined type 'System.Object' is not defined or imported
- (122:12) Predefined type 'System.Void' is not defined or imported
- (131:25) Predefined type 'System.String' is not defined or imported
- (131:12) The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
- (131:12) Predefined type 'System.Object' is not defined or imported
- (131:12) Predefined type 'System.Void' is not defined or imported
- (137:25) Predefined type 'System.String' is not defined or imported
- (137:12) The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
- (137:12) Predefined type 'System.Object' is not defined or imported
- (137:12) Predefined type 'System.Void' is not defined or imported
- (142:25) Predefined type 'System.String' is not defined or imported
- (142:12) The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
- (142:12) Predefined type 'System.Object' is not defined or imported
- (142:12) Predefined type 'System.Void' is not defined or imported
- (19:35) 'iaudzgaf_03d.ExecuteAsync()': not all code paths return a value

See CompilationErrors for detailed information


RazorLight.TemplateCompilationException: Failed to compile generated Razor template:
- (3:17) The type or namespace name 'Linq' does not exist in the namespace 'System' (are you missing an assembly reference?)
- (6:17) The type or namespace name 'Threading' does not exist in the namespace 'System' (are you missing an assembly reference?)
- (8:32) The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
- (19:35) The return type of an async method must be void, Task or Task<T>
- (19:30) The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
- (19:30) Predefined type 'System.Object' is not defined or imported
- (19:30) The type or namespace name 'Task' could not be found (are you missing a using directive or an assembly reference?)
- (19:35) 'iaudzgaf_03d.ExecuteAsync()': return type must be 'Task' to match overridden member 'TemplatePage.ExecuteAsync()'
- (19:35) The type 'Task' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Threading.Tasks, Version=4.0.10.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
- (11:8) Predefined type 'System.Void' is not defined or imported
- (11:15) Predefined type 'System.Void' is not defined or imported
- (2:4) Predefined type 'System.String' is not defined or imported
- (2:13) Predefined type 'System.String' is not defined or imported
- (28:25) Predefined type 'System.String' is not defined or imported
- (28:12) The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
- (28:12) Predefined type 'System.Object' is not defined or imported
- (28:12) Predefined type 'System.Void' is not defined or imported
- (32:25) Predefined type 'System.String' is not defined or imported
- (32:12) The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
- (32:12) Predefined type 'System.Object' is not defined or imported
- (32:12) Predefined type 'System.Void' is not defined or imported
- (39:25) Predefined type 'System.String' is not defined or imported
- (39:12) The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
- (39:12) Predefined type 'System.Object' is not defined or imported
- (39:12) Predefined type 'System.Void' is not defined or imported
- (46:25) Predefined type 'System.String' is not defined or imported
- (46:12) The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
- (46:12) Predefined type 'System.Object' is not defined or imported
- (46:12) Predefined type 'System.Void' is not defined or imported
- (54:25) Predefined type 'System.String' is not defined or imported
- (54:12) The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
- (54:12) Predefined type 'System.Object' is not defined or imported
- (54:12) Predefined type 'System.Void' is not defined or imported
- (58:25) Predefined type 'System.String' is not defined or imported
- (58:12) The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
- (58:12) Predefined type 'System.Object' is not defined or imported
- (58:12) Predefined type 'System.Void' is not defined or imported
- (63:25) Predefined type 'System.String' is not defined or imported
- (63:12) The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
- (63:12) Predefined type 'System.Object' is not defined or imported
- (63:12) Predefined type 'System.Void' is not defined or imported
- (72:25) Predefined type 'System.String' is not defined or imported
- (72:12) The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
- (72:12) Predefined type 'System.Object' is not defined or imported
- (72:12) Predefined type 'System.Void' is not defined or imported
- (80:25) Predefined type 'System.String' is not defined or imported
- (80:12) The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
- (80:12) Predefined type 'System.Object' is not defined or imported
- (80:12) Predefined type 'System.Void' is not defined or imported
- (84:25) Predefined type 'System.String' is not defined or imported
- (84:12) The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
- (84:12) Predefined type 'System.Object' is not defined or imported
- (84:12) Predefined type 'System.Void' is not defined or imported
- (92:25) Predefined type 'System.String' is not defined or imported
- (92:12) The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
- (92:12) Predefined type 'System.Object' is not defined or imported
- (92:12) Predefined type 'System.Void' is not defined or imported
- (97:25) Predefined type 'System.String' is not defined or imported
- (97:12) The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
- (97:12) Predefined type 'System.Object' is not defined or imported
- (97:12) Predefined type 'System.Void' is not defined or imported
- (102:25) Predefined type 'System.String' is not defined or imported
- (102:12) The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
- (102:12) Predefined type 'System.Object' is not defined or imported
- (102:12) Predefined type 'System.Void' is not defined or imported
- (106:25) Predefined type 'System.String' is not defined or imported
- (106:12) The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
- (106:12) Predefined type 'System.Object' is not defined or imported
- (106:12) Predefined type 'System.Void' is not defined or imported
- (111:25) Predefined type 'System.String' is not defined or imported
- (111:12) The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
- (111:12) Predefined type 'System.Object' is not defined or imported
- (111:12) Predefined type 'System.Void' is not defined or imported
- (122:25) Predefined type 'System.String' is not defined or imported
- (122:12) The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
- (122:12) Predefined type 'System.Object' is not defined or imported
- (122:12) Predefined type 'System.Void' is not defined or imported
- (131:25) Predefined type 'System.String' is not defined or imported
- (131:12) The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
- (131:12) Predefined type 'System.Object' is not defined or imported
- (131:12) Predefined type 'System.Void' is not defined or imported
- (137:25) Predefined type 'System.String' is not defined or imported
- (137:12) The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
- (137:12) Predefined type 'System.Object' is not defined or imported
- (137:12) Predefined type 'System.Void' is not defined or imported
- (142:25) Predefined type 'System.String' is not defined or imported
- (142:12) The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
- (142:12) Predefined type 'System.Object' is not defined or imported
- (142:12) Predefined type 'System.Void' is not defined or imported
- (19:35) 'iaudzgaf_03d.ExecuteAsync()': not all code paths return a value

See CompilationErrors for detailed information

   at RazorLight.Compilation.CompilationResult.EnsureSuccessful()
   at RazorLight.Templating.DefaultPageFactory.CreateFactory(String key)
   at RazorLight.Templating.DefaultPageLookup.GetPage(String key)
   at RazorLight.RazorLightEngine.Parse(String key, Object model, Type modelType, ExpandoObject viewBag, Action`1 prerenderCallback)
   at RazorLight.RazorLightEngine.Parse(String key, Object model, Type modelType, ExpandoObject viewBag)
   at RazorLight.RazorLightEngine.Parse[T](String key, T model)
   at Bit.Core.Services.RazorViewMailService.<SendWelcomeEmailAsync>d__13.MoveNext() in C:\Projects\bw-core\src\Core\Services\Implementations\RazorViewMailService.cs:line 181
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Bit.Core.Services.UserService.<RegisterUserAsync>d__22.MoveNext() in C:\Projects\bw-core\src\Core\Services\Implementations\UserService.cs:line 186
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Bit.Api.Controllers.AccountsController.<PostRegister>d__6.MoveNext() in C:\Projects\bw-core\src\Api\Controllers\AccountsController.cs:line 46
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionMethodAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextActionFilterAsync>d__25.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeNextExceptionFilterAsync>d__24.MoveNext()
Microsoft.AspNetCore.Mvc.Internal.ObjectResultExecutor:Information: Executing ObjectResult, writing value Microsoft.AspNetCore.Mvc.ControllerContext.
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker:Information: Executed action Bit.Api.Controllers.AccountsController.PostRegister (Api) in 3415.9647ms
Microsoft.AspNetCore.Hosting.Internal.WebHost:Information: Request finished in 3491.5243ms 500 application/json; charset=utf-8
The program '[10100] dotnet.exe: Program Trace' has exited with code 0 (0x0).
The program '[10100] dotnet.exe' has exited with code -1 (0xffffffff).
```

I have tried explicitly adding a reference to `System.Runtime` from nuget, but that didn't seem to change anything.

Any ideas?

**Comment by toddams** [comment]
At the moment .NET Core 2.0 is not supported, but development is in the process

**Comment by kspearrin** [comment]
@toddams 

As a follow up, I have been playing around with the library code as was able to get things working by adding the following to [`UseEntryAssemblyMetadataResolver`](https://github.com/toddams/RazorLight/blob/master/src/RazorLight/UseEntryAssemblyMetadataResolver.cs#L17):

```
#if NETSTANDARD1_6
    DependencyContext entryAssemblyDependencies = DependencyContext.Load(Assembly.GetEntryAssembly());

    foreach (CompilationLibrary compilationLibrary in entryAssemblyDependencies.CompileLibraries)
    {
        List<string> assemblyPaths = compilationLibrary.ResolveReferencePaths().ToList();
        if (assemblyPaths.Any())
        {
            metadataReferences.Add(MetadataReference.CreateFromFile(assemblyPaths.First()));
        }
    }

    // ADDED
    
    var nuget = "c:/users/kyle/.nuget/packages";
    var sysRuntime = MetadataReference.CreateFromFile(nuget + "/system.runtime/4.3.0/ref/netstandard1.5/System.Runtime.dll");
    metadataReferences.Add(sysRuntime);
    var linq = MetadataReference.CreateFromFile(nuget + "/system.linq/4.3.0/ref/netstandard1.6/System.Linq.dll");
    metadataReferences.Add(linq);
    var threading = MetadataReference.CreateFromFile(nuget + "/system.threading/4.3.0/ref/netstandard1.3/System.Threading.dll");
    metadataReferences.Add(threading);
    var tasks = MetadataReference.CreateFromFile(nuget + "/system.threading.tasks/4.3.0/ref/netstandard1.3/System.Threading.Tasks.dll");
    metadataReferences.Add(tasks);

    // END ADDED

    if (!metadataReferences.Any())
    {
        throw new RazorLightException("Can't load metadata reference from the entry assembly. " +
            "Make sure preserveCompilationContext is set to true in buildOptions section of project.json or in *.csproj file");
    }
#elif NET451
// ....
```

Obviously a hack for testing, but it seems like the `NETSTANDARD1_6` block there is not pulling in all the necessary assembly references. 

Any ideas on a proper workaround? I'm looking to make a custom build so that we can get this working for our project in the meantime (blocker for us at the moment) until you can get a proper 2.0 version out.

**Comment by mechm** [comment]
any update on this - i am getting System.TypeLoadException: 'Could not load type 'Microsoft.AspNetCore.Razor.RazorEngineHost' from assembly 'Microsoft.AspNetCore.Razor, Version=2.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'.'

**Comment by grokky1** [comment]
Could someone maybe release a temporary hotfix version with @kspearrin fix to myget? I don't know how to do such a thing, or I'd try to do it and help out. :(

**Comment by kspearrin** [comment]
I did not find a fix.

**Comment by starkmsu** [comment]
To fix "Could not load type 'Microsoft.AspNetCore.Razor.RazorEngineHost'" you need to reference Microsoft.AspNetCore.Mvc.Razor 2.0.0 directly from your project

**Comment by toddams** [comment]
I guess, this one is not relevant anymore, while 2.0 version is out

**Comment by mrychter** [comment]
for net core 2 unit test project i have this exception: Exception thrown: 'RazorLight.RazorLightException' in System.Private.CoreLib.dll

test is as simple as that:

public class TemplatingTests
    {

        [Fact]
        public async void Simple()
        {
            
            var engine = new RazorLightEngineBuilder()
                .UseMemoryCachingProvider()
                .Build();

            string template = "Hello, @Model.Name. Welcome to RazorLight repository";
            var model = new { Name = "John Doe" };

            string result = await engine.CompileRenderAsync("templateKey", template, model);
            
        }

    }

**Comment by VinzSpring** [comment]
Was this ever fixed?!

**Comment by jzabroski** [comment]
@VinzSpring You are commenting on a closed issue with 4 words. This is not helpful. It is distracting to my work day. If you have a problem, open a new issue and follow the issue template or it will be immediately closed.
