### ISSUE TITLE
Null Reference (2.0-alpha2)

### ISSUE THREAD

**Issue by kspearrin** [toddams/RazorLight#85]
I am testing `2.0.0-alpha2`, trying to run my same memory test from #84 and I am getting a null reference exception.

```
   at RazorLight.Compilation.DefaultMetadataReferenceManager.Resolve(Assembly assembly)
   at RazorLight.Compilation.RoslynCompilationService.EnsureOptions()
   at RazorLight.Compilation.RoslynCompilationService.get_ParseOptions()
   at RazorLight.Compilation.RoslynCompilationService.CreateCompilation(String compilationContent, String assemblyName)
   at RazorLight.Compilation.RoslynCompilationService.CompileAndEmit(String generatedCode)
   at RazorLight.TemplateFactoryProvider.<CreateFactoryAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at RazorLight.RazorLightEngine.<CompileTemplateAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at RazorLight.RazorLightEngine.<CompileRenderAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at RazorLight.RazorLightEngine.<CompileRenderAsync>d__6`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at RazorLight.RazorLightEngine.<CompileRenderAsync>d__5`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Tests.Program.<MainAsync>d__1.MoveNext()
```

Code
========

Sample project: [RazorLightMemoryTests.zip](https://github.com/toddams/RazorLight/files/1312930/RazorLightMemoryTests.zip)

```c#
public static void Main(string[] args)
{
    MainAsync(args).Wait();
}

public async static Task MainAsync(string[] args)
{
    var factory = new EngineFactory();
    var engine = factory.ForEmbeddedResources(typeof(Program));

    for(int i = 0; i < 10000; i++)
    {
        var model = new BaseMailModel
        {
            WebVaultUrl = "http://google.com",
            SiteName = "Google"
        };

        var htmlContent = await engine.CompileRenderAsync("Templates.Welcome", model);
        var textContent = await engine.CompileRenderAsync("Templates.Welcome.text", model);
    }
}
```

Templates are pretty basic with just Layout, Model, and Raw usage.

**Comment by toddams** [comment]
Hello @kspearrin 
The problem is that you did not set "preservecompilationcontext". I will improve an exception message for this case, same as we have in 1.0 version.

Set in your csproj file:
````xml
<PropertyGroup>
    <OutputType>Exe</OutputType>
    <PreserveCompilationContext>true</PreserveCompilationContext>
</PropertyGroup>
````
Then make **clean/rebuild** (this is important)

**Comment by SeriousM** [comment]
I get the same error with beta-3 even when I added the project property and clean/rebuild the project.
The strange thing is that the options are actually there as private field but the ParseOptions does not work.

![image](https://user-images.githubusercontent.com/462013/31443431-ba4c10e4-ae99-11e7-83da-b853b6b89e77.png)

The scenario is this:
RazorLight-beta3 is referenced by a own nuget package to encapsulare the reference to RazorLight - lets call it "My.Templating" which is compiled for .netstandard2 and net461.
A project compiled for net461 is referencing the "My.Templating" nuget package.
The error happens in the case whether I add only the necessary referenced nuget packages or all where RazorLight depends on.

Could you please help?
